### ISSUE TITLE
Meta Recipes

### ISSUE THREAD

**Issue by norlandrhagen** [pangeo-forge/pangeo-forge-recipes#395]
Hi there, 

I've been working on a recipe for [EOBS](https://github.com/pangeo-forge/staged-recipes/pull/89). I've had to split this recipe into three recipes and am wondering if there are any guidelines for "meta recipes". 

For the EOBS recipe, two variables have slightly different grids/ timesteps. I was thinking of re-indexing the data so all eight variables could be part of the same zarr store, but on further thought I would rather not modify the dataset. Instead, I split the recipe into three recipes to get rid of the xarray coord merge conflicts. Is there any way to document that these three recipes are all part of a single dataset? (perhaps in the meta.yaml or..) 

The three recipe PR's:
 - https://github.com/pangeo-forge/staged-recipes/pull/89
 - https://github.com/pangeo-forge/staged-recipes/pull/167
 - https://github.com/pangeo-forge/staged-recipes/pull/168

**Comment by cisaacstern** [comment]
Thanks for raising this question, @norlandrhagen! Probably the best way to handle this would be to:

1. Define all three of these recipes inside a single `recipe.py` module, i.e.
    
    ```python
    # recipe.py

    from pangeo_forge_recipes.recipes import XarrayZarrRecipe
    
    # ...
    eobs_tg_tn_tx_rr_hu_pp = XarrayZarrRecipe(  # ... )
    
    # ...
    eobs_wind_speed = XarrayZarrRecipe(  # ... )

    # ...
    eobs_surface_downwelling = XarrayZarrRecipe(  # ... )
    ```

2. Then specify these three recipes as a list in [the `meta.yaml` recipes section](https://pangeo-forge.readthedocs.io/en/latest/introduction_tutorial/intro_tutorial_part3.html#recipes-section), i.e.

    ```yaml
    recipes:
      - id: eobs-tg-tn-tx-rr-hu-pp
        object: "recipe:eobs-tg-tn-tx-rr-hu-pp"
      - id: eobs-wind-speed
        object: "recipe:eobs_wind_speed"
      - id: eobs-surface-downwelling
        object: "recipe:eobs_surface_downwelling"
    ```

Does that make sense and/or seem like it will work for your application? Please let me know if I can clarify further. This is definitely an under-documented area, and if this discussion can lead to a PR to improve [the recipe contribution docs](https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_cloud/recipe_contribution.html) that would be awesome. Probably
