### ISSUE TITLE
HDFReferenceRecipe failing to write lat, lon coordinate values.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-recipes#400]
While prototyping a new `HDFReferenceRecipe` for the Himawari-8 SST data https://github.com/pangeo-forge/staged-recipes/issues/173 I noted that the `lat` `lon` coordinate values are all `nan` for both the individual reference files and the multi-zarr.  This example notebook demonstrates the results of the `HDFReferenceRecipe` and the equivalent reference creation using `SingleHdf5ToZarr` and `MultiZarrToZarr` directly.

https://gist.github.com/sharkinsspatial/4cdae3a870d9b25c880308e7eefb3ff8

I can't see an obvious difference between the approach used internally by `HDFReferenceRecipe` and my direct `kerchunk` approach, any suggestions are greatly appreciated.

**Comment by rabernat** [comment]
Thanks for reporting Sean. This is ringing a bell somewhere deep in my brain, but I can't seem to find an issue for it anywhere.

@martindurant - any thoughts?

**Comment by martindurant** [comment]
```
fs = fsspec.filesystem("reference", fo="./kerchunk/reference.json", remote_protocol="file")
```
"file" should be "s3"

cf further down:
```
store = fsspec.filesystem("reference", fo=mz.translate()).get_mapper("")
```
where fsspec is autodetecting "s3" as the only remote protocol amongst the references (and this is not an anon connection, but presumably there are valid AWS creds around)

**Comment by martindurant** [comment]
So two things:
- ReferenceFileSystem should raise a different and specific exception for "yes, reference is in my list, but I failed to reach the remote file" (versus FileNotFound for no reference at all)
- Should anon=True be indicated directly in the references? Should there, in general, be the equivalent of storage_options embedded in the reference defs, as opposed to into an Intake stub? I notice that the intake stub was correctly generated in ./kerchunk/reference.yaml , including the right parameters
```yaml
sources:
  data:
    args:
      chunks: {}
      consolidated: false
      storage_options:
        fo: ./kerchunk/reference.json
        remote_options:
          anon: true
        remote_protocol: s3
        skip_instance_cache: true
        target_options: {}
        target_protocol: file
      urlpath: reference://
    description: ''
    driver: intake_xarray.xzarr.ZarrSource
```
(intake exists to not have to type out and get wrong our arguments for loading data)
